# -*- coding: utf-8 -*-
"""COM_Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-DAh8IGQbRfI4M1vE2FSwwXrMMKEYHzb
"""

import sys
import time
def vpass():
  string = str(input('Enter password :'))
  flag=0
  flag2=0
  print(len(string))
 # print(ord(string[3:12]))
  if len(string)>=10:
    if int(ord(string[0])) == 80 and int(ord(string[1])) == 65 and int(ord(string[2])) == 83:
      #if int(ord(string[3])) == 35 :
      for i in string:
        if int(ord(i)) == 35 or int(ord(i)) == 36 or int(ord(i)) == 37 or int(ord(i)) == 38 or int(ord(i)) == 64 or int(ord(i)) == 42 :
          flag=1 
      if flag==1 :
        for k in range(len(string)):
          if k < len(string)-1:
            if string[k]==string[k+1]:
              print("Invalid Password")
              break
          else:
            print("Valid Password")
      else:
        print("Invalid Password")
    else:
      print("Invalid Password")
          
  else:
     print('Invalid Password')

    
  menu()
def vemail():
  string= str(input("Enter Your Email :"))
  cse = '@cse.uiu.ac.bd'
  eee = '@eee.uiu.ac.bd'
  bba = '@bba.uiu.ac.bd'
  flag=0
  c =string.find(cse)+13
  e =string.find(eee)+13
  b =string.find(bba)+13

  print(ord(string[0]))
  if int(ord(string[0]))>= 97 and int(ord(string[0]))<=122 :
    if string.find(cse) == -1 :
      if string.find(eee) == -1:
        if string.find(bba) == -1:
          print("INvalid Email ID!!!!!!!")
        else:
          if b == len(string)-1:
             print('Valid Email ID') 
          else:
            print("INvalid Email ID!!!!!!!")
      else:
         if e == len(string)-1:
           print('Valid Email ID')
         else:
           print("INvalid Email ID!!!!!!!")
    else:
      if c == len(string)-1:
        print('Valid Email ID !!!!!!!') 
      else:
        print("INvalid Email ID!!!!!!!")   
  else:
     print('Invalid Email ID !!!!!!!')     
 
 

  menu()
def vstring():
  string = str(input('Enter your string :'))
  name = 'SAJIB'
  if len(string)==13:
    if string[0:5] == name:
      if string[5:8] >= '300' and string[5:8] <= '400':
        if string[8:11] == 'CSE' or string[8:11] == 'UIU' or string[8:11] == 'COM' :
          if string[11] == '+' or string[11] == '-':
            if int(ord(string[12])) >= 97 and int(ord(string[12])) <= 122:
              print('Valid String ')
            else:
              print('Invalid String !!!!!!!! ')
          else:
           print('INvalaid String !!!!!!!!')
        else:
          print('Invalid String !!!!!!!!')  
      else:
        print('Invalid String !!!!!!!!')  
      
    else:
      print('Invalid String !!!!!!!!!!!')  

  else:
    if len(string)==12:
      if string[0:5] == name:
        if string[5:8] >= '300' and string[5:8] <= '400':
          if string[8:11] == 'CSE' or string[8:11] == 'UIU' or string[8:11] == 'COM' :
            if int(ord(string[11])) >= 97 and int(ord(string[11])) <= 122:
              print('Valid String ')
            else:
             print('Inalaid String !!!!!!!!!!')
          else:
            print('Invalid String !!!!!!!!')  
        else:
          print('Invalid String !!!!!!!!!')  
        
      else:
        print('INvalid String !!!!!!!!!!!') 

    else: 
      print('Invalid String !!!!!!!!!!! ') 
       
  menu()

def vstring1():
  string =str(input("Enter Your string :"))
  print(string[1:4])
  end_with='gmail.com'
  
  print(ord(string[4]))
  print(ord(string[4])+1)
  print(ord(string[4])+2)
     
  if string[0]=='@' or string[0]=='#':
    if int(string[1:4]) % 2 == 0:
      if ord(string[4])+1 == ord(string[5]) and ord(string[4])+2 == ord(string[6]):
        if string[7] == '0' or string[7] == '1':
          if str(ord(string[8]))>='65' and str(ord(string[8]))<='90':
            if(string[9:12] == '152'):
              if string[12:21] == end_with:
                print("valid String")
              else:
                print("Invalid String !!!!!!!!")
            else:
              print("Invalid String !!!!!!!!")
          else:
            print("Invalid String !!!!!!!!")
        else:
          print("Invalid String !!!!!!!!")
    else:  
       print("Invalid String !!!!!!!!")               
  else:
    print("Invalid String !!!!!!!!")  

  menu()      

def vlid():
  id = str(input("Enter your UIU ID :"))
  cse='011'
  eee='111'
  bba='021'
  year_start='05'
  year_end ='22'
  trimester_end='3'
  trimester_start='10'
  p_id_start='1'
  p_id_end='999'
  print(len(id))
  print(id[0:3])
  print(id[5])
  if len(id)==9:
    if id[0:3]==cse or id[0:3]==eee or id[0:3]==bba :
      if id[3:5]>=year_start and id[3:5]<=year_end:
        if id [5]>=trimester_start and id[5]<=trimester_end:
          if id[6:9]>=p_id_start and id[6:9]<=p_id_end:
            print("valid Number")
          else:
            print("Invalid Number !!!!!")    
  else:
     print("Invalid Number !!!!!!")     
  menu()    
def quit():
  print("System in now exiting......")
  time.sleep(2)
  sys.exit()

def menu():
  print("*************Main menu*************")
  time.sleep(1)
  choice=int(input("""
               1:Validate a password
               2:Validate UIU CSE/EEE/BBA faculty email address.
               3:Validate the following string using the following criteria
               4:Validate the following string using the following criteria
               5:Validate UIU student ID
               6:Exit
               make a selection :

  """) )
  if choice == 1:
    vpass()
  elif choice == 2:
    vemail()
  elif choice == 3:
    vstring()
  elif choice == 4:
    vstring1()
  elif choice == 5:
    vlid()
  elif choice == 6:
    quit()
  else:
    menu()
menu()

n = input('Enter yout ID:  ')
if n[0:3] == '011' or n[0:3] == '111' or n[0:3] == '021' :
  if n[3:5] >= '05' and n[3:5] <= '22' :
    if n[6] >= '1' and n[6] <= '3' :
      if n[7:-1] >= '05' and n[7:-1] <= '22' :
    print('valid')
  else:  
   print('InValid')
else:
  print('Invalid')

n ='hddghfk'
print(n[-1])